### PR TITLE
Implementation changed

### PR DESCRIPTION
**Pull request by Gheorghe-Valer**
Check differences and merge.

### CODE REVIEW

**Review by Gheorghe-Valer-Scurtu — CHANGES_REQUESTED** [review]
Change the code, avoiding to modify existing funcionality. 

1. App.controller.js 
    function: newFeature: function()  (current line 17)

**Comment by Gheorghe-Valer** [comment]
The changes were applied

**Review by Gheorghe-Valer-Scurtu — APPROVED** [review]
All OK!

**Review by Logali-Group — APPROVED** [review]
Approved

**Pull request merged**
